#!/bin/bash

path=$(dirname "${0}")

# install script
cp "${path}"/params-shell.sh /bin/params-shell

# install conf
mkdir /var/lib/params-shell/
cp "${path}"/params-shell.conf /var/lib/params-shell/params-shell.conf

# install lang
cp "${path}"/po/FR/params-shell.mo /usr/share/locale/fr/LC_MESSAGES/params-shell.mo

